server:
    port: 9099
#  port: 0

spring:
  application:
    name: api-gateway
  profiles:
    active: LOCAL
  config:
    import: configserver:http://configuration-server:8888
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true   # имена из eureka]
          lower-case-service-id: true

#logging:
#  level:
#    org.springframework.cloud.gateway: DEBUG
#    reactor.netty.http.client: DEBUG